# Generated by Django 5.0.6 on 2024-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
